# Generated by Django 5.2.6 on 2025-10-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bola basket', 'Bola Basket'), ('bola tenis', 'Bola Tenis'), ('bola ping-pong', 'Bola Ping-pong')], max_length=20),
        ),
    ]
